//import Navbar from "./components/navbar/Navbar";
import NavbarNoSSr from "./components/navbar/NavbarNoSSr";
import { AuthContextProvider } from "./helpers/AuthContextProvider";

// app/layout.js
export const metadata = {
    title: "Prime",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {

    return (
            <html lang="en">
                <body>
                    <AuthContextProvider >
                     <NavbarNoSSr/>
                    {children}
                    </AuthContextProvider>
                </body>
            </html>
    )
}
